### ISSUE TITLE
Normalize email before comparing

### ISSUE THREAD

**Issue by duong-fear** [torusresearch/CustomAuth#208]
![image](https://user-images.githubusercontent.com/97949506/185077602-571246f7-43e7-436a-a8ff-17054bbd97e7.png)
Hey guys
Found this error message while login with CustomAuth
> `paramsemail` not equal to `body.email`

And as you can see thats because case-sensitive problem.
Any idea to fix this. thank you

**Comment by chaitanyapotti** [comment]
please use the field `isVerifierIdCaseSensitive` to determine this
