### ISSUE TITLE
Could't connect to Ropsten node

### ISSUE THREAD

**Issue by hylian-flute** [torusresearch/CustomAuth#214]
If you specify `testnet` for `network` in the argument of constructor, the connection to node will fail. Is there a workaround for this issue?
I think it has something to do with Infura deprecating support for Ropsten.

```js
const torus = new CustomAuth({
  baseUrl: "http://localhost:3000/serviceworker/",
  network: "testnet",
});
```

```
Error: CONNECTION ERROR: Couldn't connect to node https://ropsten.infura.io/v3/b8cdb0e4cff24599a286bf8e87ff1c96.
    at Object.ConnectionError (errors.js?490f:66:1)
    at Object.InvalidConnection (errors.js?490f:36:1)
    at HttpProvider.failed (index.js?64e4:136:1)
```

**Comment by chaitanyapotti** [comment]
Please refer to this github discussion
https://github.com/orgs/Web3Auth/discussions/685

**Comment by odanado** [comment]
This issue can be resolved by bringing the library version up to date
ref: https://github.com/orgs/Web3Auth/discussions/911
