### ISSUE TITLE
ENGINE_MAP import issue

### ISSUE THREAD

**Issue by nisa10880** [torusresearch/CustomAuth#268]
ENGINE_MAP is not imported corectly in CustomAuth/tree/master/src/utils/helpers.ts file.

✘ [ERROR] No matching export in "node_modules/bowser/src/bowser.js" for import "ENGINE_MAP" node_modules/@toruslabs/customauth/dist/customauth.esm.js:16:17: 16 │ import Bowser, { ENGINE_MAP } from 'bowser';

**Comment by chaitanyapotti** [comment]
This is fixed now in 11.4.3
Thanks for reporting
