### ISSUE TITLE
'triggerLogin' function remains locked after auth window closure

### ISSUE THREAD

**Issue by madcent** [torusresearch/CustomAuth#297]
### Description

We are currently utilizing the CustomAuth to manage user sign-up and sign-in processes, as well as enabling them to sign transactions using the private key associated with their generated addresses. The module has generally functioned well, but we've recently encountered a specific issue with the Google authentication flow.

The problem arises with the 'triggerLogin' function. We've observed that if a user closes the auth window, the 'triggerLogin' function unexpectedly remains in a locked state. I've taken the initiative to investigate this issue further and have prepared a [patch](https://github.com/torusresearch/CustomAuth/files/12083885/setupTimer_fix.patch)
 that seems to resolve the problem. It will be great if a maintainer could review this proposed fix and consider integrating it into an upcoming release. Please feel free to provide any feedback or suggest modifications if required. 

### Steps to reproduce:
1. create a new google verifier https://dashboard.web3auth.io/home/team/[YOUR-COMPANY]/customauth ;
2. init the CustomAuth like:
```
const torus = new CustomAuth({
    baseUrl: `${window.location.origin}/serviceworker`,
    enableLogging: false,
    network: 'mainnet',
    web3AuthClientId: 'test',
  });
await torus.init({ skipSw: false });
try {
  await torus.triggerLogin({
      typeOfLogin: 'google',
      verifier: '<YOUR VERIFIER IDENTIFIER>',
      clientId: '<YOUR CLIENT ID>',
    });
} finally {
  console.log('triggerLogin has been resolved');
}
```
3. google auth window will be opened;
4. close the window;

#### Expected Behaviour
5. torus.triggerLogin function is "released" and 'triggerLogin has been resolved' message appears in the console;

#### Actual Behaviour
5. torus.triggerLogin function is "locked" and no 'triggerLogin has been resolved' message appears.

**Comment by chaitanyapotti** [comment]
This is fixed in latest version
